### ISSUE TITLE
defaultBundleUrl should be 7.0.3-ga4 in ide 3.1.0 ga1 

### ISSUE THREAD

**Issue by fanqi** [liferay/liferay-ide#111]
in ide 3.1.0 ga1,defaultBundleUrl is https://cdn.lfrs.sl/releases.liferay.com/portal/7.0.2-ga3/liferay-ce-portal-tomcat-7.0-ga3-20160804222206210.zip
but lastest bundle url is
https://cdn.lfrs.sl/releases.liferay.com/portal/7.0.3-ga4/liferay-ce-portal-tomcat-7.0-ga4-20170613175008905.zip.

Where should I configure it?

**Comment by gamerson** [comment]
Thanks @fanqi  for the report.  We will fix this in the upcoming release of Liferay IDE 3.1.1.
