### ISSUE TITLE
Eclipse IDE hangs with liferay-ide

### ISSUE THREAD

**Issue by le-zell** [liferay/liferay-ide#270]
Hi,

see attached video to see the issue.

Eclipse is not responding at all.

Plateform : Win7 + Eclipse 2021-06 + liferay-ide ( on Oracle JDK 8, 11 or eclipse packaged jre)

https://user-images.githubusercontent.com/11717695/134465600-bdeb9bbf-4bd1-40ac-8a47-18fc8879ea2e.mp4

No response after 8h of work...don't known what to do except killing eclipse process. 

Restarting eclipse is ok but the problem comes back after a few minutes...

**Comment by Seiphon** [comment]
Hi @le-zell, thanks for reportting this issue to us. However we can not reproduce this issue on our IDE, If possible can you offer a test project which can lead this issue happen. Thank you so much!

**Comment by le-zell** [comment]
Hi @Seiphon  and thank you for your interest, i am a big fan of Liferay (and liferay IDE).

Unfortunately, I can't do that because it's a private project.

What does LiferayIDE do when it's blocked on "PropertiesFileLookup" ? Can i uncheked/undo this ? You think it's the type (project with 15 modules) of maven project that causes the issue ?

Thanks in advance , i don't know that to do. I'm stucked. On Ubuntu Linux, it's nearly worst, Eclipse goes to OOM.

I notice that when i uninstall LiferayIDE, it's "working" (Eclipse stays alive) but Eclipse keeps downloading sources/javaodoc indefinitely...

And I notice that i have always a conflict on Eclipse dependencies with BndTools...and that Liferay IDE is not compatible with the last EclipseIDE 2021-09. So i stay on 2021-06.

**Comment by Seiphon** [comment]
Hi @le-zell  I do find a bug when parsing property files for jsp editor, this bug will lead to a infinit loop, so the Eclipse will be blocked. I think if you don't keep the jsp files open with 'jsp editor', this problem would not happen.

For this bug, I will fix it as soon as posible, please waitting for the next release of LiferayIDE.

And for the conflict on dependencies with bndtools, can you give more details?

For EclipseIDE 2021-9, we have tested 2021-09-M1 on linux and 2021-09-R on windows, we don't meet the compatible issue you mentioned. Could you please try our latest release version? if you still meet compatible  problems, please fell free to let me know.

LBNL, thank you so much for helping improve our product!

**Comment by le-zell** [comment]
Hi @Seiphon good news to hear !

OK for the JSP, i will close them as soon as edited and saved.

And for the Eclipse 2021-09, i have successfully tested tody the IDE with Liferay IDE, it's indeed working, sorry for the mis-report.

Thanks for all

**Comment by Seiphon** [comment]
Hi @le-zell, I created a jira ticket for this issue, so you can track the issue [here](https://issues.liferay.com/browse/IDE-5039).
