### ISSUE TITLE
Support for macOS AArch64

### ISSUE THREAD

**Issue by haba713** [liferay/liferay-ide#380]
Will Liferay IDE support macOS AArch64 in the near future? Eclipse has supported it since [2021-12](https://www.eclipse.org/downloads/packages/release/2021-12/r). The last MacBook with an Intel CPU was manufactured in 2021.

**Comment by joshchong** [comment]
Thanks for your inquiry. Our team will be looking into the feasibility of adding AArch64 / ARM64 support. With that said, any incompatibility should reside only in the installer and not with Liferay Dev Studio itself.

As a workaround, when encountering an error during the install, proceed past it to continue the installation as usual. This should generate the zip file located within the folder selected at the beginning of the install. Manually unzip this zip file to get a working installation.

**Comment by joshchong** [comment]
We just released a new version that should allow the macOS installer to work with ARM64. @haba713 please try out the [new installer here](https://github.com/liferay/liferay-ide/releases/tag/3.10.1) and let us know if you run into any issues. Thanks!

**Comment by haba713** [comment]
The installer works fine now, many thanks!

**Comment by haba713** [comment]
There are still two minor issues in MacOS (Sonoma 14.6.1):
- Left-clicking the installer.app gives an error: "...cannot be opened because the developer cannot be verified." Right-click the installer.app and select Open from the context menu to continue.
-  The setup screen opens [initially in full screen size](https://github.com/user-attachments/assets/109ba857-019c-4832-91d8-a467458f7d80), but you can adjust the size or just continue.

But they are different issues, very minor, and I think this issue can be closed.
