### ISSUE TITLE
problem creating service builder

### ISSUE THREAD

**Issue by mirkoperillo** [liferay/liferay-ide#57]
I cannot create a Liferay Service Builder, because in creating form is impossible to select any liferay plugin available in workspace, so the creation cannot be ended.

As workaround I created manually a service.xml file in WEB-INF folder of plugin. 
After manually creation service.xml is correctly identified by service builder plugin.

Environment
- eclipse Luna
- liferay IDE 2.2.2.201501300730-ga3
- liferary sdk 6.2.2

**Comment by gamerson** [comment]
Hello @mirkoperillo  thanks for taking time to report this issue.  Can you please repost your issue here on our project's JIRA issue tracker?

https://issues.liferay.com/browse/IDE

thanks!
