### ISSUE TITLE
service builder build silent failure

### ISSUE THREAD

**Issue by mirkoperillo** [liferay/liferay-ide#58]
If I have some error in my service.xml and I try to run Build Services command nothing happens ( no class is created and no error log is presented)

Only running from liferay > maven menu liferay:build-service goal I have a clear log about problems in service.xml.

Environment:
- eclipse Luna
- liferay IDE 2.2.2.201501300730-ga3
- liferay sdk 6.2.2

**Comment by gamerson** [comment]
Hello @mirkoperillo  thanks for taking time to report this issue.  Can you please repost your issue here on our project's JIRA issue tracker?

https://issues.liferay.com/browse/IDE

thanks!
