### ISSUE TITLE
How to Override user.timezone=GMT

### ISSUE THREAD

**Issue by phancox** [liferay/liferay-ide#92]
Using IDE 3.0.1 GA2 I am unable to set user.timezone to anything other GMT.
It appears to be set in the launch configuration but if changed will immediately revert to GMT.
Any attempt to override in the server configuration screen are ignored.

**Comment by gamerson** [comment]
hey @phancox  can you open a ticket with this information here? https://issues.liferay.com/browse/IDE    We will take a look at that and see what we can find.

**Comment by gamerson** [comment]
Ah nevermind! you beat me to it! https://issues.liferay.com/browse/IDE-177

Actually we should create a new ticket because it seems we may have had a regression in this area.

**Comment by phancox** [comment]
Created https://issues.liferay.com/browse/IDE-2884

**Comment by gamerson** [comment]
thanks @phancox  for the report.
